//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaP.Miservicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Miservicio.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarCredenciales", ReplyAction="*")]
        BibliotecaP.Miservicio.VerificarCredencialesResponse VerificarCredenciales(BibliotecaP.Miservicio.VerificarCredencialesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarCredenciales", ReplyAction="*")]
        System.Threading.Tasks.Task<BibliotecaP.Miservicio.VerificarCredencialesResponse> VerificarCredencialesAsync(BibliotecaP.Miservicio.VerificarCredencialesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarUsuario", ReplyAction="*")]
        BibliotecaP.Miservicio.VerificarUsuarioResponse VerificarUsuario(BibliotecaP.Miservicio.VerificarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<BibliotecaP.Miservicio.VerificarUsuarioResponse> VerificarUsuarioAsync(BibliotecaP.Miservicio.VerificarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdUsuario", ReplyAction="*")]
        BibliotecaP.Miservicio.IdUsuarioResponse IdUsuario(BibliotecaP.Miservicio.IdUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IdUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<BibliotecaP.Miservicio.IdUsuarioResponse> IdUsuarioAsync(BibliotecaP.Miservicio.IdUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearUsuario", ReplyAction="*")]
        BibliotecaP.Miservicio.CrearUsuarioResponse CrearUsuario(BibliotecaP.Miservicio.CrearUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<BibliotecaP.Miservicio.CrearUsuarioResponse> CrearUsuarioAsync(BibliotecaP.Miservicio.CrearUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento VerlibrosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Verlibros", ReplyAction="*")]
        BibliotecaP.Miservicio.VerlibrosResponse Verlibros(BibliotecaP.Miservicio.VerlibrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Verlibros", ReplyAction="*")]
        System.Threading.Tasks.Task<BibliotecaP.Miservicio.VerlibrosResponse> VerlibrosAsync(BibliotecaP.Miservicio.VerlibrosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idUsuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarLibro", ReplyAction="*")]
        BibliotecaP.Miservicio.AgregarLibroResponse AgregarLibro(BibliotecaP.Miservicio.AgregarLibroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarLibro", ReplyAction="*")]
        System.Threading.Tasks.Task<BibliotecaP.Miservicio.AgregarLibroResponse> AgregarLibroAsync(BibliotecaP.Miservicio.AgregarLibroRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idUsuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerTusLibors", ReplyAction="*")]
        BibliotecaP.Miservicio.VerTusLiborsResponse VerTusLibors(BibliotecaP.Miservicio.VerTusLiborsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerTusLibors", ReplyAction="*")]
        System.Threading.Tasks.Task<BibliotecaP.Miservicio.VerTusLiborsResponse> VerTusLiborsAsync(BibliotecaP.Miservicio.VerTusLiborsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idPrestamo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarLibro", ReplyAction="*")]
        BibliotecaP.Miservicio.EliminarLibroResponse EliminarLibro(BibliotecaP.Miservicio.EliminarLibroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarLibro", ReplyAction="*")]
        System.Threading.Tasks.Task<BibliotecaP.Miservicio.EliminarLibroResponse> EliminarLibroAsync(BibliotecaP.Miservicio.EliminarLibroRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarCredencialesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarCredenciales", Namespace="http://tempuri.org/", Order=0)]
        public BibliotecaP.Miservicio.VerificarCredencialesRequestBody Body;
        
        public VerificarCredencialesRequest() {
        }
        
        public VerificarCredencialesRequest(BibliotecaP.Miservicio.VerificarCredencialesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarCredencialesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contraseña;
        
        public VerificarCredencialesRequestBody() {
        }
        
        public VerificarCredencialesRequestBody(string usuario, string contraseña) {
            this.usuario = usuario;
            this.contraseña = contraseña;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarCredencialesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarCredencialesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BibliotecaP.Miservicio.VerificarCredencialesResponseBody Body;
        
        public VerificarCredencialesResponse() {
        }
        
        public VerificarCredencialesResponse(BibliotecaP.Miservicio.VerificarCredencialesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarCredencialesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerificarCredencialesResult;
        
        public VerificarCredencialesResponseBody() {
        }
        
        public VerificarCredencialesResponseBody(bool VerificarCredencialesResult) {
            this.VerificarCredencialesResult = VerificarCredencialesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public BibliotecaP.Miservicio.VerificarUsuarioRequestBody Body;
        
        public VerificarUsuarioRequest() {
        }
        
        public VerificarUsuarioRequest(BibliotecaP.Miservicio.VerificarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contraseña;
        
        public VerificarUsuarioRequestBody() {
        }
        
        public VerificarUsuarioRequestBody(string usuario, string contraseña) {
            this.usuario = usuario;
            this.contraseña = contraseña;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public BibliotecaP.Miservicio.VerificarUsuarioResponseBody Body;
        
        public VerificarUsuarioResponse() {
        }
        
        public VerificarUsuarioResponse(BibliotecaP.Miservicio.VerificarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerificarUsuarioResult;
        
        public VerificarUsuarioResponseBody() {
        }
        
        public VerificarUsuarioResponseBody(bool VerificarUsuarioResult) {
            this.VerificarUsuarioResult = VerificarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IdUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IdUsuario", Namespace="http://tempuri.org/", Order=0)]
        public BibliotecaP.Miservicio.IdUsuarioRequestBody Body;
        
        public IdUsuarioRequest() {
        }
        
        public IdUsuarioRequest(BibliotecaP.Miservicio.IdUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IdUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contraseña;
        
        public IdUsuarioRequestBody() {
        }
        
        public IdUsuarioRequestBody(string usuario, string contraseña) {
            this.usuario = usuario;
            this.contraseña = contraseña;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IdUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IdUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public BibliotecaP.Miservicio.IdUsuarioResponseBody Body;
        
        public IdUsuarioResponse() {
        }
        
        public IdUsuarioResponse(BibliotecaP.Miservicio.IdUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IdUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IdUsuarioResult;
        
        public IdUsuarioResponseBody() {
        }
        
        public IdUsuarioResponseBody(int IdUsuarioResult) {
            this.IdUsuarioResult = IdUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearUsuario", Namespace="http://tempuri.org/", Order=0)]
        public BibliotecaP.Miservicio.CrearUsuarioRequestBody Body;
        
        public CrearUsuarioRequest() {
        }
        
        public CrearUsuarioRequest(BibliotecaP.Miservicio.CrearUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contraseña;
        
        public CrearUsuarioRequestBody() {
        }
        
        public CrearUsuarioRequestBody(string usuario, string contraseña) {
            this.usuario = usuario;
            this.contraseña = contraseña;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public BibliotecaP.Miservicio.CrearUsuarioResponseBody Body;
        
        public CrearUsuarioResponse() {
        }
        
        public CrearUsuarioResponse(BibliotecaP.Miservicio.CrearUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CrearUsuarioResult;
        
        public CrearUsuarioResponseBody() {
        }
        
        public CrearUsuarioResponseBody(bool CrearUsuarioResult) {
            this.CrearUsuarioResult = CrearUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerlibrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Verlibros", Namespace="http://tempuri.org/", Order=0)]
        public BibliotecaP.Miservicio.VerlibrosRequestBody Body;
        
        public VerlibrosRequest() {
        }
        
        public VerlibrosRequest(BibliotecaP.Miservicio.VerlibrosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class VerlibrosRequestBody {
        
        public VerlibrosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerlibrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerlibrosResponse", Namespace="http://tempuri.org/", Order=0)]
        public BibliotecaP.Miservicio.VerlibrosResponseBody Body;
        
        public VerlibrosResponse() {
        }
        
        public VerlibrosResponse(BibliotecaP.Miservicio.VerlibrosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerlibrosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VerlibrosResult;
        
        public VerlibrosResponseBody() {
        }
        
        public VerlibrosResponseBody(string VerlibrosResult) {
            this.VerlibrosResult = VerlibrosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarLibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarLibro", Namespace="http://tempuri.org/", Order=0)]
        public BibliotecaP.Miservicio.AgregarLibroRequestBody Body;
        
        public AgregarLibroRequest() {
        }
        
        public AgregarLibroRequest(BibliotecaP.Miservicio.AgregarLibroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarLibroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idLibro;
        
        public AgregarLibroRequestBody() {
        }
        
        public AgregarLibroRequestBody(string idUsuario, string idLibro) {
            this.idUsuario = idUsuario;
            this.idLibro = idLibro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarLibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarLibroResponse", Namespace="http://tempuri.org/", Order=0)]
        public BibliotecaP.Miservicio.AgregarLibroResponseBody Body;
        
        public AgregarLibroResponse() {
        }
        
        public AgregarLibroResponse(BibliotecaP.Miservicio.AgregarLibroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarLibroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AgregarLibroResult;
        
        public AgregarLibroResponseBody() {
        }
        
        public AgregarLibroResponseBody(bool AgregarLibroResult) {
            this.AgregarLibroResult = AgregarLibroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerTusLiborsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerTusLibors", Namespace="http://tempuri.org/", Order=0)]
        public BibliotecaP.Miservicio.VerTusLiborsRequestBody Body;
        
        public VerTusLiborsRequest() {
        }
        
        public VerTusLiborsRequest(BibliotecaP.Miservicio.VerTusLiborsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerTusLiborsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idUsuario;
        
        public VerTusLiborsRequestBody() {
        }
        
        public VerTusLiborsRequestBody(string idUsuario) {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerTusLiborsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerTusLiborsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BibliotecaP.Miservicio.VerTusLiborsResponseBody Body;
        
        public VerTusLiborsResponse() {
        }
        
        public VerTusLiborsResponse(BibliotecaP.Miservicio.VerTusLiborsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerTusLiborsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VerTusLiborsResult;
        
        public VerTusLiborsResponseBody() {
        }
        
        public VerTusLiborsResponseBody(string VerTusLiborsResult) {
            this.VerTusLiborsResult = VerTusLiborsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarLibroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarLibro", Namespace="http://tempuri.org/", Order=0)]
        public BibliotecaP.Miservicio.EliminarLibroRequestBody Body;
        
        public EliminarLibroRequest() {
        }
        
        public EliminarLibroRequest(BibliotecaP.Miservicio.EliminarLibroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarLibroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idPrestamo;
        
        public EliminarLibroRequestBody() {
        }
        
        public EliminarLibroRequestBody(string idPrestamo) {
            this.idPrestamo = idPrestamo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarLibroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarLibroResponse", Namespace="http://tempuri.org/", Order=0)]
        public BibliotecaP.Miservicio.EliminarLibroResponseBody Body;
        
        public EliminarLibroResponse() {
        }
        
        public EliminarLibroResponse(BibliotecaP.Miservicio.EliminarLibroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarLibroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EliminarLibroResult;
        
        public EliminarLibroResponseBody() {
        }
        
        public EliminarLibroResponseBody(bool EliminarLibroResult) {
            this.EliminarLibroResult = EliminarLibroResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : BibliotecaP.Miservicio.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<BibliotecaP.Miservicio.WebServiceSoap>, BibliotecaP.Miservicio.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BibliotecaP.Miservicio.VerificarCredencialesResponse BibliotecaP.Miservicio.WebServiceSoap.VerificarCredenciales(BibliotecaP.Miservicio.VerificarCredencialesRequest request) {
            return base.Channel.VerificarCredenciales(request);
        }
        
        public bool VerificarCredenciales(string usuario, string contraseña) {
            BibliotecaP.Miservicio.VerificarCredencialesRequest inValue = new BibliotecaP.Miservicio.VerificarCredencialesRequest();
            inValue.Body = new BibliotecaP.Miservicio.VerificarCredencialesRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            BibliotecaP.Miservicio.VerificarCredencialesResponse retVal = ((BibliotecaP.Miservicio.WebServiceSoap)(this)).VerificarCredenciales(inValue);
            return retVal.Body.VerificarCredencialesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BibliotecaP.Miservicio.VerificarCredencialesResponse> BibliotecaP.Miservicio.WebServiceSoap.VerificarCredencialesAsync(BibliotecaP.Miservicio.VerificarCredencialesRequest request) {
            return base.Channel.VerificarCredencialesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BibliotecaP.Miservicio.VerificarCredencialesResponse> VerificarCredencialesAsync(string usuario, string contraseña) {
            BibliotecaP.Miservicio.VerificarCredencialesRequest inValue = new BibliotecaP.Miservicio.VerificarCredencialesRequest();
            inValue.Body = new BibliotecaP.Miservicio.VerificarCredencialesRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            return ((BibliotecaP.Miservicio.WebServiceSoap)(this)).VerificarCredencialesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BibliotecaP.Miservicio.VerificarUsuarioResponse BibliotecaP.Miservicio.WebServiceSoap.VerificarUsuario(BibliotecaP.Miservicio.VerificarUsuarioRequest request) {
            return base.Channel.VerificarUsuario(request);
        }
        
        public bool VerificarUsuario(string usuario, string contraseña) {
            BibliotecaP.Miservicio.VerificarUsuarioRequest inValue = new BibliotecaP.Miservicio.VerificarUsuarioRequest();
            inValue.Body = new BibliotecaP.Miservicio.VerificarUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            BibliotecaP.Miservicio.VerificarUsuarioResponse retVal = ((BibliotecaP.Miservicio.WebServiceSoap)(this)).VerificarUsuario(inValue);
            return retVal.Body.VerificarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BibliotecaP.Miservicio.VerificarUsuarioResponse> BibliotecaP.Miservicio.WebServiceSoap.VerificarUsuarioAsync(BibliotecaP.Miservicio.VerificarUsuarioRequest request) {
            return base.Channel.VerificarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<BibliotecaP.Miservicio.VerificarUsuarioResponse> VerificarUsuarioAsync(string usuario, string contraseña) {
            BibliotecaP.Miservicio.VerificarUsuarioRequest inValue = new BibliotecaP.Miservicio.VerificarUsuarioRequest();
            inValue.Body = new BibliotecaP.Miservicio.VerificarUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            return ((BibliotecaP.Miservicio.WebServiceSoap)(this)).VerificarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BibliotecaP.Miservicio.IdUsuarioResponse BibliotecaP.Miservicio.WebServiceSoap.IdUsuario(BibliotecaP.Miservicio.IdUsuarioRequest request) {
            return base.Channel.IdUsuario(request);
        }
        
        public int IdUsuario(string usuario, string contraseña) {
            BibliotecaP.Miservicio.IdUsuarioRequest inValue = new BibliotecaP.Miservicio.IdUsuarioRequest();
            inValue.Body = new BibliotecaP.Miservicio.IdUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            BibliotecaP.Miservicio.IdUsuarioResponse retVal = ((BibliotecaP.Miservicio.WebServiceSoap)(this)).IdUsuario(inValue);
            return retVal.Body.IdUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BibliotecaP.Miservicio.IdUsuarioResponse> BibliotecaP.Miservicio.WebServiceSoap.IdUsuarioAsync(BibliotecaP.Miservicio.IdUsuarioRequest request) {
            return base.Channel.IdUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<BibliotecaP.Miservicio.IdUsuarioResponse> IdUsuarioAsync(string usuario, string contraseña) {
            BibliotecaP.Miservicio.IdUsuarioRequest inValue = new BibliotecaP.Miservicio.IdUsuarioRequest();
            inValue.Body = new BibliotecaP.Miservicio.IdUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            return ((BibliotecaP.Miservicio.WebServiceSoap)(this)).IdUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BibliotecaP.Miservicio.CrearUsuarioResponse BibliotecaP.Miservicio.WebServiceSoap.CrearUsuario(BibliotecaP.Miservicio.CrearUsuarioRequest request) {
            return base.Channel.CrearUsuario(request);
        }
        
        public bool CrearUsuario(string usuario, string contraseña) {
            BibliotecaP.Miservicio.CrearUsuarioRequest inValue = new BibliotecaP.Miservicio.CrearUsuarioRequest();
            inValue.Body = new BibliotecaP.Miservicio.CrearUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            BibliotecaP.Miservicio.CrearUsuarioResponse retVal = ((BibliotecaP.Miservicio.WebServiceSoap)(this)).CrearUsuario(inValue);
            return retVal.Body.CrearUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BibliotecaP.Miservicio.CrearUsuarioResponse> BibliotecaP.Miservicio.WebServiceSoap.CrearUsuarioAsync(BibliotecaP.Miservicio.CrearUsuarioRequest request) {
            return base.Channel.CrearUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<BibliotecaP.Miservicio.CrearUsuarioResponse> CrearUsuarioAsync(string usuario, string contraseña) {
            BibliotecaP.Miservicio.CrearUsuarioRequest inValue = new BibliotecaP.Miservicio.CrearUsuarioRequest();
            inValue.Body = new BibliotecaP.Miservicio.CrearUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contraseña = contraseña;
            return ((BibliotecaP.Miservicio.WebServiceSoap)(this)).CrearUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BibliotecaP.Miservicio.VerlibrosResponse BibliotecaP.Miservicio.WebServiceSoap.Verlibros(BibliotecaP.Miservicio.VerlibrosRequest request) {
            return base.Channel.Verlibros(request);
        }
        
        public string Verlibros() {
            BibliotecaP.Miservicio.VerlibrosRequest inValue = new BibliotecaP.Miservicio.VerlibrosRequest();
            inValue.Body = new BibliotecaP.Miservicio.VerlibrosRequestBody();
            BibliotecaP.Miservicio.VerlibrosResponse retVal = ((BibliotecaP.Miservicio.WebServiceSoap)(this)).Verlibros(inValue);
            return retVal.Body.VerlibrosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BibliotecaP.Miservicio.VerlibrosResponse> BibliotecaP.Miservicio.WebServiceSoap.VerlibrosAsync(BibliotecaP.Miservicio.VerlibrosRequest request) {
            return base.Channel.VerlibrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<BibliotecaP.Miservicio.VerlibrosResponse> VerlibrosAsync() {
            BibliotecaP.Miservicio.VerlibrosRequest inValue = new BibliotecaP.Miservicio.VerlibrosRequest();
            inValue.Body = new BibliotecaP.Miservicio.VerlibrosRequestBody();
            return ((BibliotecaP.Miservicio.WebServiceSoap)(this)).VerlibrosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BibliotecaP.Miservicio.AgregarLibroResponse BibliotecaP.Miservicio.WebServiceSoap.AgregarLibro(BibliotecaP.Miservicio.AgregarLibroRequest request) {
            return base.Channel.AgregarLibro(request);
        }
        
        public bool AgregarLibro(string idUsuario, string idLibro) {
            BibliotecaP.Miservicio.AgregarLibroRequest inValue = new BibliotecaP.Miservicio.AgregarLibroRequest();
            inValue.Body = new BibliotecaP.Miservicio.AgregarLibroRequestBody();
            inValue.Body.idUsuario = idUsuario;
            inValue.Body.idLibro = idLibro;
            BibliotecaP.Miservicio.AgregarLibroResponse retVal = ((BibliotecaP.Miservicio.WebServiceSoap)(this)).AgregarLibro(inValue);
            return retVal.Body.AgregarLibroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BibliotecaP.Miservicio.AgregarLibroResponse> BibliotecaP.Miservicio.WebServiceSoap.AgregarLibroAsync(BibliotecaP.Miservicio.AgregarLibroRequest request) {
            return base.Channel.AgregarLibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<BibliotecaP.Miservicio.AgregarLibroResponse> AgregarLibroAsync(string idUsuario, string idLibro) {
            BibliotecaP.Miservicio.AgregarLibroRequest inValue = new BibliotecaP.Miservicio.AgregarLibroRequest();
            inValue.Body = new BibliotecaP.Miservicio.AgregarLibroRequestBody();
            inValue.Body.idUsuario = idUsuario;
            inValue.Body.idLibro = idLibro;
            return ((BibliotecaP.Miservicio.WebServiceSoap)(this)).AgregarLibroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BibliotecaP.Miservicio.VerTusLiborsResponse BibliotecaP.Miservicio.WebServiceSoap.VerTusLibors(BibliotecaP.Miservicio.VerTusLiborsRequest request) {
            return base.Channel.VerTusLibors(request);
        }
        
        public string VerTusLibors(string idUsuario) {
            BibliotecaP.Miservicio.VerTusLiborsRequest inValue = new BibliotecaP.Miservicio.VerTusLiborsRequest();
            inValue.Body = new BibliotecaP.Miservicio.VerTusLiborsRequestBody();
            inValue.Body.idUsuario = idUsuario;
            BibliotecaP.Miservicio.VerTusLiborsResponse retVal = ((BibliotecaP.Miservicio.WebServiceSoap)(this)).VerTusLibors(inValue);
            return retVal.Body.VerTusLiborsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BibliotecaP.Miservicio.VerTusLiborsResponse> BibliotecaP.Miservicio.WebServiceSoap.VerTusLiborsAsync(BibliotecaP.Miservicio.VerTusLiborsRequest request) {
            return base.Channel.VerTusLiborsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BibliotecaP.Miservicio.VerTusLiborsResponse> VerTusLiborsAsync(string idUsuario) {
            BibliotecaP.Miservicio.VerTusLiborsRequest inValue = new BibliotecaP.Miservicio.VerTusLiborsRequest();
            inValue.Body = new BibliotecaP.Miservicio.VerTusLiborsRequestBody();
            inValue.Body.idUsuario = idUsuario;
            return ((BibliotecaP.Miservicio.WebServiceSoap)(this)).VerTusLiborsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BibliotecaP.Miservicio.EliminarLibroResponse BibliotecaP.Miservicio.WebServiceSoap.EliminarLibro(BibliotecaP.Miservicio.EliminarLibroRequest request) {
            return base.Channel.EliminarLibro(request);
        }
        
        public bool EliminarLibro(string idPrestamo) {
            BibliotecaP.Miservicio.EliminarLibroRequest inValue = new BibliotecaP.Miservicio.EliminarLibroRequest();
            inValue.Body = new BibliotecaP.Miservicio.EliminarLibroRequestBody();
            inValue.Body.idPrestamo = idPrestamo;
            BibliotecaP.Miservicio.EliminarLibroResponse retVal = ((BibliotecaP.Miservicio.WebServiceSoap)(this)).EliminarLibro(inValue);
            return retVal.Body.EliminarLibroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BibliotecaP.Miservicio.EliminarLibroResponse> BibliotecaP.Miservicio.WebServiceSoap.EliminarLibroAsync(BibliotecaP.Miservicio.EliminarLibroRequest request) {
            return base.Channel.EliminarLibroAsync(request);
        }
        
        public System.Threading.Tasks.Task<BibliotecaP.Miservicio.EliminarLibroResponse> EliminarLibroAsync(string idPrestamo) {
            BibliotecaP.Miservicio.EliminarLibroRequest inValue = new BibliotecaP.Miservicio.EliminarLibroRequest();
            inValue.Body = new BibliotecaP.Miservicio.EliminarLibroRequestBody();
            inValue.Body.idPrestamo = idPrestamo;
            return ((BibliotecaP.Miservicio.WebServiceSoap)(this)).EliminarLibroAsync(inValue);
        }
    }
}
